export const MODELS = {
  TEXT_MODEL: 'deepseek-chat',
};

export function findVideoModel(modelId) {
  return (
    FAL_VIDEO_MODELS.find((m) => m.id === modelId || m.legacyIds?.includes(modelId)) ||
    FAL_VIDEO_MODELS[0]
  );
}

// ─── fal.ai Image Model Registry ─────────────────────────────────────────────
export const FAL_IMAGE_MODELS = [
  {
    id: 'fal-ai/flux/dev',
    label: 'FLUX.1 Dev',
    sublabel: 'Black Forest Labs · Open weights',
    supportsRef: true,
    editEndpoint: 'fal-ai/flux/dev/image-to-image',
    tags: ['fast', 'reference'],
    recommended: true,
    speed: 'fast',
    arParam: 'image_size',
    arValue: 'portrait_16_9',
  },
  {
    id: 'fal-ai/nano-banana-2',
    label: 'Nano Banana 2',
    sublabel: 'Fast Text-to-Image',
    supportsRef: false,
    editEndpoint: 'fal-ai/nano-banana-2/edit',
    editImageField: 'image_urls',
    tags: ['fast'],
    recommended: false,
    speed: 'fast',
    arParam: 'aspect_ratio',
    arValue: '9:16',
  },
  {
    id: 'fal-ai/flux-pro/v1.1',
    label: 'FLUX 1.1 Pro',
    sublabel: 'Black Forest Labs · High quality',
    supportsRef: false,
    editEndpoint: null,
    tags: ['high-quality'],
    recommended: false,
    speed: 'medium',
    arParam: 'image_size',
    arValue: 'portrait_16_9',
  },
  {
    id: 'fal-ai/flux-pro/v1.1-ultra',
    label: 'FLUX 1.1 Pro Ultra',
    sublabel: 'Black Forest Labs · 2K resolution',
    supportsRef: false,
    editEndpoint: null,
    tags: ['2K', 'cinematic'],
    recommended: false,
    speed: 'medium',
    arParam: 'aspect_ratio',
    arValue: '9:16',
  },
  {
    id: 'fal-ai/recraft-v3',
    label: 'Recraft V3',
    sublabel: 'Recraft · Great text & styles',
    supportsRef: false,
    editEndpoint: null,
    tags: ['typography'],
    recommended: false,
    speed: 'medium',
    arParam: 'image_size',
    arValue: 'portrait_16_9',
    defaultStyle: 'realistic_image',
  },
  {
    id: 'vertex-imagen4',
    label: 'Imagen 4 (Vertex AI)',
    sublabel: 'Google Vertex AI · Photorealistic Image Generation',
    sdk: 'vertex',
    supportsRef: false,
    editEndpoint: null,
    tags: ['photorealistic'],
    recommended: false,
    speed: 'medium',
    arParam: 'aspect_ratio',
    arValue: '9:16',
  },
];

// ─── fal.ai Video Model Registry ─────────────────────────────────────────────
export const FAL_VIDEO_MODELS = [
  {
    id: 'fal-ai/sora-2/text-to-video/pro',
    label: 'Sora 2 Pro',
    sublabel: 'OpenAI · Ultra-High Fidelity',
    sdk: 'fal',
    supportsI2V: true,
    i2vEndpoint: 'fal-ai/sora-2/image-to-video/pro',
    videoInputKind: 'sora',
    allowedDurations: [4, 8, 12, 16, 20],
    allowedDurationsT2v: [4, 8, 12, 16, 20],
    allowedDurationsI2v: [4, 8, 12, 16, 20],
    hasAudio: true,
    maxDuration: 20,
    recommended: true,
    speed: 'slow',
  },
  {
    id: 'fal-ai/kling-video/v3/pro/text-to-video',
    label: 'Kling 3.0 Pro',
    sublabel: 'Kuaishou · Cinematic Masterpiece',
    sdk: 'fal',
    supportsI2V: true,
    i2vEndpoint: 'fal-ai/kling-video/v3/pro/image-to-video',
    videoInputKind: 'kling-v3',
    allowedDurations: [5, 10, 20],
    allowedDurationsI2v: [5, 10],
    hasAudio: true,
    maxDuration: 20,
    recommended: false,
    speed: 'medium',
  },
  {
    id: 'fal-ai/veo3.1',
    label: 'Veo 3.1 Pro',
    sublabel: 'Google · Highest Quality + Native Audio',
    sdk: 'fal',
    supportsI2V: false,
    videoInputKind: 'veo',
    allowedDurations: [4, 6, 8, 12],
    veo1080pRequires8s: true,
    hasAudio: true,
    maxDuration: 12,
    recommended: false,
    speed: 'medium',
  },
  {
    id: 'fal-ai/veo3.1/lite',
    label: 'Veo 3.1 Lite',
    sublabel: 'Google · Fast Preview + Native Audio',
    sdk: 'fal',
    supportsI2V: true,
    i2vEndpoint: 'fal-ai/veo3.1/lite/image-to-video',
    videoInputKind: 'veo',
    allowedDurations: [4, 6, 8],
    veo1080pRequires8s: true,
    hasAudio: true,
    maxDuration: 8,
    recommended: false,
    speed: 'fast',
  },
  {
    id: 'fal-ai/veo2',
    label: 'Veo 2 (Classic)',
    sublabel: 'Google · Legacy Video Generation',
    sdk: 'fal',
    legacyIds: ['fal-ai/veo-2'],
    supportsI2V: true,
    i2vEndpoint: 'fal-ai/veo2/image-to-video',
    videoInputKind: 'veo2',
    allowedDurations: [5, 6, 7, 8],
    hasAudio: false,
    maxDuration: 8,
    recommended: false,
    speed: 'medium',
  },

  {
    id: 'fal-ai/minimax/hailuo-2.3/pro/text-to-video',
    label: 'Hailuo 2.3 Pro',
    sublabel: 'MiniMax · Photorealistic',
    sdk: 'fal',
    supportsI2V: true,
    i2vEndpoint: 'fal-ai/minimax/hailuo-2.3/pro/image-to-video',
    videoInputKind: 'minimax',
    allowedDurations: [6, 10],
    hasAudio: false,
    maxDuration: 10,
    recommended: false,
    speed: 'medium',
  },
  {
    id: 'bytedance/seedance-2.0/fast/text-to-video',
    label: 'Seedance 2.0',
    sublabel: 'ByteDance · Realistic Physics',
    sdk: 'fal',
    supportsI2V: true,
    i2vEndpoint: 'bytedance/seedance-2.0/image-to-video',
    videoInputKind: 'seedance',
    allowedDurations: [5, 10],
    hasAudio: true,
    maxDuration: 15,
    recommended: false,
    speed: 'fast',
  },
  {
    id: 'alibaba/happy-horse/text-to-video',
    label: 'Happy Horse 1.0',
    sublabel: 'Alibaba · 1080p + Audio',
    sdk: 'fal',
    supportsI2V: true,
    i2vEndpoint: 'alibaba/happy-horse/image-to-video',
    videoInputKind: 'happy-horse',
    allowedDurations: [5, 10],
    hasAudio: true,
    maxDuration: 15,
    recommended: false,
    speed: 'medium',
  },

  {
    id: 'fal-ai/luma-dream-machine/ray-2',
    label: 'Luma Ray 2',
    sublabel: 'Luma · Versatile T2V/I2V',
    sdk: 'fal',
    supportsI2V: true,
    i2vEndpoint: 'fal-ai/luma-dream-machine/ray-2/image-to-video',
    videoInputKind: 'luma-ray2',
    allowedDurations: [5, 9],
    hasAudio: false,
    maxDuration: 9,
    recommended: false,
    speed: 'medium',
  },
  {
    id: 'fal-ai/wan-i2v',
    label: 'WAN 2.1 I2V',
    sublabel: 'Alibaba · Reliable Open Model',
    sdk: 'fal',
    supportsI2V: true,
    i2vEndpoint: 'fal-ai/wan-i2v',
    videoInputKind: 'wan-i2v',
    allowedDurations: [6],
    hasAudio: false,
    maxDuration: 6,
    recommended: false,
    speed: 'medium',
  },
  {
    id: 'fal-ai/mochi-v1',
    label: 'Mochi 1',
    sublabel: 'Genmo · High Fidelity Motion',
    sdk: 'fal',
    supportsI2V: false,
    videoInputKind: 'mochi',
    allowedDurations: [5, 10],
    hasAudio: false,
    maxDuration: 10,
    recommended: false,
    speed: 'fast',
  },
  {
    id: 'fal-ai/hunyuan-video',
    label: 'Hunyuan Video',
    sublabel: 'Tencent · Large Scale Open',
    sdk: 'fal',
    supportsI2V: false,
    videoInputKind: 'hunyuan',
    allowedDurations: [5, 10],
    hasAudio: false,
    maxDuration: 10,
    recommended: false,
    speed: 'medium',
  },
  {
    id: 'vertex-veo3.1-pro',
    label: 'Veo 3.1 Pro (Vertex AI)',
    sublabel: 'Google Vertex AI · Highest Quality + Native Audio',
    sdk: 'vertex',
    supportsI2V: true,
    allowedDurations: [5, 8],
    hasAudio: true,
    maxDuration: 8,
    recommended: false,
    speed: 'slow',
  },
  {
    id: 'vertex-veo3.1-lite',
    label: 'Veo 3.1 Lite (Vertex AI)',
    sublabel: 'Google Vertex AI · Fast Preview + Native Audio',
    sdk: 'vertex',
    supportsI2V: true,
    allowedDurations: [5, 8],
    hasAudio: true,
    maxDuration: 8,
    recommended: false,
    speed: 'medium',
  },
];

export const DEFAULT_IMAGE_MODEL_ID = 'fal-ai/nano-banana-2';
export const DEFAULT_VIDEO_MODEL_ID = 'fal-ai/veo3.1/lite';
