export const MODELS = {
  // Text & Prompt Generation (unchanged)
  TEXT_MODEL: 'deepseek-chat',
};

// ─── fal.ai Image Model Registry ─────────────────────────────────────────────
export const FAL_IMAGE_MODELS = [
  {
    id: 'fal-ai/flux/dev',
    label: 'FLUX.1 Dev',
    sublabel: 'Black Forest Labs · Open weights',
    supportsRef: true,
    editEndpoint: 'fal-ai/flux/dev/image-to-image',
    tags: ['fast', 'reference'],
    recommended: true,
    speed: 'fast',
    arParam: 'image_size',
    arValue: 'portrait_16_9'
  },
  {
    id: 'fal-ai/nano-banana-2',
    label: 'Nano Banana 2',
    sublabel: 'Fast Text-to-Image',
    supportsRef: false,
    editEndpoint: null,
    tags: ['fast'],
    recommended: false,
    speed: 'fast',
    arParam: 'aspect_ratio',
    arValue: '9:16'
  },
  {
    id: 'fal-ai/flux-pro/v1.1',
    label: 'FLUX 1.1 Pro',
    sublabel: 'Black Forest Labs · High quality',
    supportsRef: false,
    editEndpoint: null,
    tags: ['high-quality'],
    recommended: false,
    speed: 'medium',
    arParam: 'image_size',
    arValue: 'portrait_16_9'
  },
  {
    id: 'fal-ai/flux-pro/v1.1-ultra',
    label: 'FLUX 1.1 Pro Ultra',
    sublabel: 'Black Forest Labs · 2K resolution',
    supportsRef: false,
    editEndpoint: null,
    tags: ['2K', 'cinematic'],
    recommended: false,
    speed: 'medium',
    arParam: 'aspect_ratio', // Ultra takes aspect_ratio
    arValue: '9:16'
  },
  {
    id: 'fal-ai/recraft-v3',
    label: 'Recraft V3',
    sublabel: 'Recraft · Great text & styles',
    supportsRef: false,
    editEndpoint: null,
    tags: ['typography'],
    recommended: false,
    speed: 'medium',
    arParam: 'image_size',
    arValue: 'portrait_16_9'
  }
];

// ─── fal.ai Video Model Registry ─────────────────────────────────────────────
export const FAL_VIDEO_MODELS = [
  // ─── TIER 1: THE GIANTS (2026 TOP END) ───
  {
    id: 'fal-ai/sora-2/text-to-video/pro',
    label: 'Sora 2 Pro',
    sublabel: 'OpenAI · Ultra-High Fidelity',
    supportsI2V: true,
    i2vEndpoint: 'fal-ai/sora-2/image-to-video/pro',
    inputSchema: 'kling',
    allowedDurations: [10, 15, 25],
    hasAudio: true,
    maxDuration: 25,
    recommended: true,
    speed: 'slow',
  },
  {
    id: 'fal-ai/kling-video/v3/pro/text-to-video',
    label: 'Kling 3.0 Pro',
    sublabel: 'Kuaishou · Cinematic Masterpiece',
    supportsI2V: true,
    i2vEndpoint: 'fal-ai/kling-video/v3/pro/image-to-video',
    inputSchema: 'kling',
    allowedDurations: [5, 10, 20],
    hasAudio: true,
    maxDuration: 20,
    recommended: false,
    speed: 'medium',
  },
  {
    id: 'fal-ai/veo3.1',
    label: 'Veo 3.1 Pro',
    sublabel: 'Google · Highest Quality + Native Audio',
    supportsI2V: false,
    inputSchema: 'veo',
    allowedDurations: [4, 6, 8, 12],
    hasAudio: true,
    maxDuration: 12,
    recommended: false,
    speed: 'medium',
  },
  {
    id: 'fal-ai/veo3.1/lite',
    label: 'Veo 3.1 Lite',
    sublabel: 'Google · Fast Preview + Native Audio',
    supportsI2V: false,
    inputSchema: 'veo',
    allowedDurations: [4, 6, 8],
    hasAudio: true,
    maxDuration: 8,
    recommended: false,
    speed: 'fast',
  },
  {
    id: 'fal-ai/veo-2',
    label: 'Veo 2 (Classic)',
    sublabel: 'Google · Legacy Video Generation',
    supportsI2V: false,
    inputSchema: 'veo',
    allowedDurations: [5, 10],
    hasAudio: false,
    maxDuration: 10,
    recommended: false,
    speed: 'medium',
  },

  // ─── TIER 2: SPECIALIZED & FAST ───
  {
    id: 'fal-ai/minimax/hailuo-2.3/pro/text-to-video',
    label: 'Hailuo 2.3 Pro',
    sublabel: 'MiniMax · Photorealistic',
    supportsI2V: true,
    i2vEndpoint: 'fal-ai/minimax/hailuo-2.3/pro/image-to-video',
    inputSchema: 'minimax',
    allowedDurations: [6, 10],
    hasAudio: false,
    maxDuration: 10,
    recommended: false,
    speed: 'medium',
  },
  {
    id: 'bytedance/seedance-2.0/fast/text-to-video',
    label: 'Seedance 2.0',
    sublabel: 'ByteDance · Realistic Physics',
    supportsI2V: true,
    i2vEndpoint: 'bytedance/seedance-2.0/image-to-video',
    inputSchema: 'wan',
    allowedDurations: [5, 10],
    hasAudio: false,
    maxDuration: 10,
    recommended: false,
    speed: 'fast',
  },
  {
    id: 'alibaba/happy-horse/text-to-video',
    label: 'Happy Horse 1.0',
    sublabel: 'Alibaba · 1080p + Audio',
    supportsI2V: true,
    i2vEndpoint: 'alibaba/happy-horse/image-to-video',
    inputSchema: 'wan',
    allowedDurations: [5, 10],
    hasAudio: true,
    maxDuration: 10,
    recommended: false,
    speed: 'medium',
  },

  // ─── TIER 3: OPEN SOURCE & STABLE ───
  {
    id: 'fal-ai/luma-dream-machine/ray-2',
    label: 'Luma Ray 2',
    sublabel: 'Luma · Versatile T2V/I2V',
    supportsI2V: true,
    i2vEndpoint: 'fal-ai/luma-dream-machine/ray-2/image-to-video',
    inputSchema: 'luma',
    allowedDurations: [5, 9],
    hasAudio: false,
    maxDuration: 9,
    recommended: false,
    speed: 'medium',
  },
  {
    id: 'fal-ai/wan-i2v',
    label: 'WAN 2.1 I2V',
    sublabel: 'Alibaba · Reliable Open Model',
    supportsI2V: true,
    i2vEndpoint: 'fal-ai/wan-i2v',
    inputSchema: 'wan',
    allowedDurations: [6],
    hasAudio: false,
    maxDuration: 6,
    recommended: false,
    speed: 'medium',
  },
  {
    id: 'fal-ai/mochi-v1',
    label: 'Mochi 1',
    sublabel: 'Genmo · High Fidelity Motion',
    supportsI2V: false,
    inputSchema: 'luma',
    allowedDurations: [5, 10],
    hasAudio: false,
    maxDuration: 10,
    recommended: false,
    speed: 'fast',
  },
  {
    id: 'fal-ai/hunyuan-video',
    label: 'Hunyuan Video',
    sublabel: 'Tencent · Large Scale Open',
    supportsI2V: false,
    inputSchema: 'luma',
    allowedDurations: [5, 10],
    hasAudio: false,
    maxDuration: 10,
    recommended: false,
    speed: 'medium',
  }
];

export const DEFAULT_IMAGE_MODEL_ID = FAL_IMAGE_MODELS[0].id;
export const DEFAULT_VIDEO_MODEL_ID = FAL_VIDEO_MODELS[0].id;
