// Mirrors backend/models.js — single source of truth for UI
export const FAL_IMAGE_MODELS = [
  {
    id: 'fal-ai/flux/dev',
    label: 'FLUX.1 Dev',
    sublabel: 'Black Forest Labs · Open weights',
    supportsRef: true,
    tags: ['fast', 'reference'],
    recommended: true,
    speed: 'fast',
  },
  {
    id: 'fal-ai/nano-banana-2',
    label: 'Nano Banana 2',
    sublabel: 'Fast Text-to-Image',
    supportsRef: false,
    tags: ['fast'],
    recommended: false,
    speed: 'fast',
  },
  {
    id: 'fal-ai/flux-pro/v1.1',
    label: 'FLUX 1.1 Pro',
    sublabel: 'Black Forest Labs · High quality',
    supportsRef: false,
    tags: ['high-quality'],
    recommended: false,
    speed: 'medium',
  },
  {
    id: 'fal-ai/flux-pro/v1.1-ultra',
    label: 'FLUX 1.1 Pro Ultra',
    sublabel: 'Black Forest Labs · 2K resolution',
    supportsRef: false,
    tags: ['2K', 'cinematic'],
    recommended: false,
    speed: 'medium',
  },
  {
    id: 'fal-ai/recraft-v3',
    label: 'Recraft V3',
    sublabel: 'Recraft · Great text & styles',
    supportsRef: false,
    tags: ['typography'],
    recommended: false,
    speed: 'medium',
  }
];

export const FAL_VIDEO_MODELS = [
  {
    id: 'fal-ai/luma-dream-machine/ray-2',
    label: 'Luma Ray 2',
    sublabel: 'Luma · Text & Image to Video',
    supportsI2V: true,
    allowedDurations: [5, 9],
    hasAudio: false,
    maxDuration: 9,
    recommended: true,
    speed: 'medium',
  },
  {
    id: 'fal-ai/wan-i2v',
    label: 'WAN 2.1 I2V',
    sublabel: 'Alibaba · Open Source I2V',
    supportsI2V: true,
    allowedDurations: [6],
    hasAudio: false,
    maxDuration: 6,
    recommended: false,
    speed: 'medium',
  },
  {
    id: 'fal-ai/veo3.1',
    label: 'Veo 3.1',
    sublabel: 'Google · High quality with Audio',
    supportsI2V: false,
    allowedDurations: [4, 6, 8],
    hasAudio: true,
    maxDuration: 8,
    recommended: false,
    speed: 'medium',
  },
  {
    id: 'fal-ai/veo3.1/lite',
    label: 'Veo 3.1 Lite',
    sublabel: 'Google · Fast Preview with Audio',
    supportsI2V: false,
    allowedDurations: [4, 6, 8],
    hasAudio: true,
    maxDuration: 8,
    recommended: false,
    speed: 'fast',
  },
  {
    id: 'fal-ai/kling-video/v2.6/pro/text-to-video',
    label: 'Kling 2.6 Pro',
    sublabel: 'Kuaishou · V2.6 with Audio',
    supportsI2V: true,
    allowedDurations: [5, 10],
    hasAudio: true,
    maxDuration: 10,
    recommended: false,
    speed: 'medium',
  },
  {
    id: 'fal-ai/kling-video/v2.5-turbo/pro/text-to-video',
    label: 'Kling 2.5 Pro',
    sublabel: 'Kuaishou · V2.5 Pro (No Audio)',
    supportsI2V: true,
    allowedDurations: [5, 10],
    hasAudio: false,
    maxDuration: 10,
    recommended: false,
    speed: 'medium',
  },
  {
    id: 'fal-ai/minimax/video-01',
    label: 'Minimax Video 01',
    sublabel: 'Minimax · Hailuo T2V',
    supportsI2V: false,
    allowedDurations: [6],
    hasAudio: false,
    maxDuration: 6,
    recommended: false,
    speed: 'fast',
  },
  {
    id: 'fal-ai/hunyuan-video',
    label: 'Hunyuan Video',
    sublabel: 'Tencent · Open Source',
    supportsI2V: false,
    allowedDurations: [5, 10],
    hasAudio: false,
    maxDuration: 10,
    recommended: false,
    speed: 'medium',
  }
];

export const DEFAULT_IMAGE_MODEL_ID = FAL_IMAGE_MODELS[0].id;
export const DEFAULT_VIDEO_MODEL_ID = FAL_VIDEO_MODELS[0].id;
