// Mirrors backend/models.js — single source of truth for UI
export const FAL_IMAGE_MODELS = [
  {
    id: 'fal-ai/nano-banana-2',
    label: 'Nano Banana 2',
    sublabel: 'Gemini 3.1 Flash Image · Google',
    supportsRef: true,
    tags: ['fast', 'reference'],
    recommended: true,
    speed: 'fast',
  },
  {
    id: 'fal-ai/nano-banana-pro',
    label: 'Nano Banana Pro',
    sublabel: 'Gemini 3 Pro Image · Google',
    supportsRef: true,
    tags: ['high-quality', 'reference'],
    recommended: false,
    speed: 'medium',
  },
  {
    id: 'fal-ai/flux-pro-v1.1-ultra',
    label: 'FLUX 1.1 Pro Ultra',
    sublabel: 'Black Forest Labs · 2K resolution',
    supportsRef: false,
    tags: ['2K', 'cinematic'],
    recommended: false,
    speed: 'medium',
  },
  {
    id: 'fal-ai/flux-dev',
    label: 'FLUX.1 Dev',
    sublabel: 'Black Forest Labs · Open weights',
    supportsRef: false,
    tags: ['open-source'],
    recommended: false,
    speed: 'fast',
  },
  {
    id: 'fal-ai/ideogram-v3',
    label: 'Ideogram V3',
    sublabel: 'Ideogram · Best for text-in-image',
    supportsRef: false,
    tags: ['typography'],
    recommended: false,
    speed: 'medium',
  },
  {
    id: 'fal-ai/bytedance-seedream-v4',
    label: 'Seedream 4.0',
    sublabel: 'ByteDance · Fast & vibrant',
    supportsRef: false,
    tags: ['fast'],
    recommended: false,
    speed: 'fast',
  },
];

export const FAL_VIDEO_MODELS = [
  {
    id: 'fal-ai/veo3.1',
    label: 'Veo 3.1',
    sublabel: 'Google DeepMind · Image-to-video · Native audio',
    supportsI2V: true,
    hasAudio: true,
    maxDuration: 8,
    recommended: true,
    speed: 'slow',
  },
  {
    id: 'fal-ai/veo3.1/fast',
    label: 'Veo 3.1 Fast',
    sublabel: 'Google DeepMind · Faster, cheaper',
    supportsI2V: true,
    hasAudio: true,
    maxDuration: 8,
    recommended: false,
    speed: 'medium',
  },
  {
    id: 'fal-ai/kling-video-v2.1-pro',
    label: 'Kling 2.1 Pro',
    sublabel: 'Kuaishou · Great motion quality',
    supportsI2V: true,
    hasAudio: false,
    maxDuration: 10,
    recommended: false,
    speed: 'medium',
  },
  {
    id: 'fal-ai/kling-video-v3-pro',
    label: 'Kling 3.0 Pro',
    sublabel: 'Kuaishou · Multi-shot · Native audio',
    supportsI2V: true,
    hasAudio: true,
    maxDuration: 10,
    recommended: false,
    speed: 'medium',
  },
  {
    id: 'fal-ai/bytedance-seedance-v1-pro-text-to-video',
    label: 'Seedance 1.0 Pro',
    sublabel: 'ByteDance · High quality',
    supportsI2V: true,
    hasAudio: false,
    maxDuration: 8,
    recommended: false,
    speed: 'medium',
  },
  {
    id: 'fal-ai/bytedance-seedance-2.0-text-to-video',
    label: 'Seedance 2.0',
    sublabel: 'ByteDance · Cinematic · Native audio',
    supportsI2V: true,
    hasAudio: true,
    maxDuration: 8,
    recommended: false,
    speed: 'medium',
  },
  {
    id: 'fal-ai/sora-2-text-to-video',
    label: 'Sora 2',
    sublabel: 'OpenAI · State-of-the-art',
    supportsI2V: true,
    hasAudio: true,
    maxDuration: 10,
    recommended: false,
    speed: 'slow',
  },
];

export const DEFAULT_IMAGE_MODEL_ID = FAL_IMAGE_MODELS[0].id;
export const DEFAULT_VIDEO_MODEL_ID = FAL_VIDEO_MODELS[0].id;
